/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg412_budgetapp;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JComboBox;

/**
 *
 * @author aim5627
 */
public class Analytics_BudgetUI extends javax.swing.JFrame {

    AnalyticsCntl parent;
    String username;
    ArrayList<Budget> budgetList;
    ArrayList<Category> categoryList;
    
    String currentSelectedBudget;
    /**
     * Creates new form Analytics_BudgetUI
     */
    public Analytics_BudgetUI() {
        initComponents();
    }
    
    public Analytics_BudgetUI(AnalyticsCntl p, String u, ArrayList<Budget> bl, ArrayList<Category> cl) {
        parent = p;
        username = u;
        budgetList = bl;
        categoryList = cl;
        initComponents();
        
        String[] budgetNamesList = new String[budgetList.size()];
        
        for(int i = 0; i<budgetList.size(); i++)
        {
            budgetNamesList[i] = budgetList.get(i).getName();
        }
        budgetCB.setModel(new JComboBox<>(budgetNamesList).getModel());
        
        currentSelectedBudget = budgetCB.getSelectedItem().toString();
        
        for(int i = 0; i<categoryList.size(); i++)
        {
            if(categoryList.get(i).getBudgetName().equals(currentSelectedBudget))
            {
                categoryTable.setText(categoryTable.getText() + categoryList.get(i).getName() + "\t\t" + 
                        String.valueOf(categoryList.get(i).getAmount()) + "\t\t" + 
                        String.valueOf(categoryList.get(i).getCurrentAmount()) + "\n");
            }
        }
        
        if(categoryTable.getText().equals(""))
        {
            categoryTable.setText("No category information available");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        budgetCB = new javax.swing.JComboBox<>();
        budgetBtn = new javax.swing.JButton();
        budgetLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTextArea();
        catNameLbl = new javax.swing.JLabel();
        totalAmountLbl = new javax.swing.JLabel();
        amountLeftLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setText("Budgets");

        budgetCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        budgetBtn.setText("Open Budget");
        budgetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetBtnActionPerformed(evt);
            }
        });

        budgetLbl.setText("Budget:");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        categoryTable.setColumns(20);
        categoryTable.setRows(5);
        jScrollPane2.setViewportView(categoryTable);

        catNameLbl.setText("Category Name");

        totalAmountLbl.setText("Total Amount");

        amountLeftLbl.setText("Amount Left");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(budgetLbl)
                        .addGap(18, 18, 18)
                        .addComponent(budgetCB, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(budgetBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(backBtn)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(catNameLbl)
                        .addGap(91, 91, 91)
                        .addComponent(totalAmountLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(amountLeftLbl)
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(budgetCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(budgetBtn)
                    .addComponent(budgetLbl))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catNameLbl)
                    .addComponent(totalAmountLbl)
                    .addComponent(amountLeftLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        parent.backBtnPressed();
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void budgetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetBtnActionPerformed
        currentSelectedBudget = budgetCB.getSelectedItem().toString();
        categoryTable.setText("");
        for(int i = 0; i<categoryList.size(); i++)
        {
            if(categoryList.get(i).getBudgetName().equals(currentSelectedBudget))
            {
                categoryTable.setText(categoryTable.getText() + categoryList.get(i).getName() + "\t\t" + 
                        String.valueOf(categoryList.get(i).getAmount()) + "\t\t" + 
                        String.valueOf(categoryList.get(i).getCurrentAmount()) + "\n");
            }
        }
        
        if(categoryTable.getText().equals(""))
        {
            categoryTable.setText("No category information available");
        }
    }//GEN-LAST:event_budgetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analytics_BudgetUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analytics_BudgetUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analytics_BudgetUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analytics_BudgetUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analytics_BudgetUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLeftLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton budgetBtn;
    private javax.swing.JComboBox<String> budgetCB;
    private javax.swing.JLabel budgetLbl;
    private javax.swing.JLabel catNameLbl;
    private javax.swing.JTextArea categoryTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel totalAmountLbl;
    // End of variables declaration//GEN-END:variables
}
