/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg412_budgetapp;

import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 *
 * @author aim5627
 */
public class Analytics_CategoryPurchasesUI extends javax.swing.JFrame {
    
    AnalyticsCntl parent;
    String username;
    ArrayList<Budget> budgetList;
    ArrayList<Category> categoryList;
    ArrayList<Transaction> transactionList;
    String currentSelectedBudget;
    String currentSelectedCategory;

    /**
     * Creates new form Analytics_CategoryPurchasesUI
     */
    public Analytics_CategoryPurchasesUI() {
        System.out.println("Analytics_CategoryPurchasesUI.constructor1");
        initComponents();
    }
    
    public Analytics_CategoryPurchasesUI(AnalyticsCntl p, String u, ArrayList<Budget> bl, ArrayList<Category> cl, ArrayList<Transaction> tl) {
        System.out.println("Analytics_CategoryPurchasesUI.constructor2");
        parent = p;
        username = u;
        budgetList = bl;
        categoryList = cl;
        transactionList = tl;
        initComponents();
        
        String[] budgetNamesList = new String[budgetList.size()];
        
        for(int i = 0; i<budgetList.size(); i++)
        {
            budgetNamesList[i] = budgetList.get(i).getName();
        }
        budgetCB.setModel(new JComboBox<>(budgetNamesList).getModel());
        currentSelectedBudget = budgetCB.getSelectedItem().toString();

        ArrayList<String> tempCatAL = new ArrayList<String>();
        for(int i = 0; i<categoryList.size(); i++)
        {
            if(currentSelectedBudget.equals(categoryList.get(i).getBudgetName()))
            {
                tempCatAL.add(categoryList.get(i).getName());
            }
        }
        String[] categoryNamesList = new String[tempCatAL.size()];
        for(int i = 0; i<tempCatAL.size(); i++)
        {
            categoryNamesList[i] = tempCatAL.get(i);
        }            
        categoryCB.setModel(new JComboBox<>(categoryNamesList).getModel());
        currentSelectedCategory = categoryCB.getSelectedItem().toString();
        
        for(int i = 0; i<transactionList.size(); i++)
        {
            if(transactionList.get(i).getCategoryName().equals(currentSelectedCategory))
            {
                transactionTable.setText(transactionTable.getText() + transactionList.get(i).getName() + "\t\t" + 
                    String.valueOf(transactionList.get(i).getMonth()) + "/" + String.valueOf(transactionList.get(i).getDay() + "/" + String.valueOf(transactionList.get(i).getAmount())) + "\t\t" + 
                    String.valueOf(transactionList.get(i).getAmount()) + "\n"); 
            }
        }
        
        if(transactionTable.getText().equals(""))
        {
            transactionTable.setText("No transaction information available");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        budgetCB = new javax.swing.JComboBox<>();
        budgetLbl = new javax.swing.JLabel();
        budgetBtn = new javax.swing.JButton();
        categoryBtn = new javax.swing.JButton();
        categoryCB = new javax.swing.JComboBox<>();
        categoryLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeWindow(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setText("Budgets / Categories");

        budgetCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        budgetLbl.setText("Budget:");

        budgetBtn.setText("Search Budgets");
        budgetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetBtnActionPerformed(evt);
            }
        });

        categoryBtn.setText("Open Category");
        categoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryBtnActionPerformed(evt);
            }
        });

        categoryCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        categoryLbl.setText("Category:");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        transactionTable.setColumns(20);
        transactionTable.setRows(5);
        jScrollPane2.setViewportView(transactionTable);

        jLabel2.setText("Transaction Name");

        jLabel3.setText("Date of Transaction");

        jLabel4.setText("Transaction Amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(budgetLbl)
                                            .addComponent(categoryLbl))
                                        .addGap(34, 34, 34))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(categoryCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(budgetCB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(categoryBtn)
                                            .addComponent(budgetBtn)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 25, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(budgetCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(budgetLbl)
                    .addComponent(budgetBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryBtn)
                    .addComponent(categoryCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryBtnActionPerformed
        System.out.println("Analytics_CategoryPurchasesUI.categoryBtnActionPerformed");
        currentSelectedCategory = categoryCB.getSelectedItem().toString();
        transactionTable.setText("");
        
        for(int i = 0; i<transactionList.size(); i++)
        {
            if(transactionList.get(i).getCategoryName().equals(currentSelectedCategory))
            {
                transactionTable.setText(transactionTable.getText() + transactionList.get(i).getName() + "\t\t" + 
                    String.valueOf(transactionList.get(i).getMonth()) + "/" + String.valueOf(transactionList.get(i).getDay() + "/" + String.valueOf(transactionList.get(i).getAmount())) + "\t\t" + 
                    String.valueOf(transactionList.get(i).getAmount()) + "\n"); 
            }
        }
        
        if(transactionTable.getText().equals(""))
        {
            transactionTable.setText("No transaction information available");
        }
        
    }//GEN-LAST:event_categoryBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        System.out.println("Analytics_CategoryPurchasesUI.backBtnActionPerformed");
        parent.backBtnPressed();
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void budgetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetBtnActionPerformed
        System.out.println("Analytics_CategoryPurchasesUI.budgetBtnActionPerformed");
        currentSelectedBudget = budgetCB.getSelectedItem().toString();
        ArrayList<String> tempCatAL = new ArrayList<String>();
        for(int i = 0; i<categoryList.size(); i++)
        {
            if(currentSelectedBudget.equals(categoryList.get(i).getBudgetName()))
            {
                tempCatAL.add(categoryList.get(i).getName());
            }
        }
        String[] categoryNamesList = new String[tempCatAL.size()];
        for(int i = 0; i<tempCatAL.size(); i++)
        {
            categoryNamesList[i] = tempCatAL.get(i);
        }            
        categoryCB.setModel(new JComboBox<>(categoryNamesList).getModel());
    }//GEN-LAST:event_budgetBtnActionPerformed

    private void closeWindow(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeWindow
        System.out.println("Analytics_CategoryPurchasesUI.closeWindow");
        parent.closeWindow();
    }//GEN-LAST:event_closeWindow

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analytics_CategoryPurchasesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analytics_CategoryPurchasesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analytics_CategoryPurchasesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analytics_CategoryPurchasesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analytics_CategoryPurchasesUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton budgetBtn;
    private javax.swing.JComboBox<String> budgetCB;
    private javax.swing.JLabel budgetLbl;
    private javax.swing.JButton categoryBtn;
    private javax.swing.JComboBox<String> categoryCB;
    private javax.swing.JLabel categoryLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea transactionTable;
    // End of variables declaration//GEN-END:variables
}
