/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg412_budgetapp;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author aim5627
 */
public class BudgetUI extends javax.swing.JFrame {

    String viewType;
    String username;
    ArrayList<Budget> budgetList;
    BudgetCntl parent;
    int position;
    
    /**
     * Creates new form BudgetUI
     */
    public BudgetUI() {
        initComponents();
    }
   
    //new budget
    public BudgetUI(BudgetCntl p, String v, String u)
    {
        System.out.println("BudgetUI.constructor1");
        initComponents();
        parent = p;
        username = u;
        viewType = v;
        budgetDropdown.setVisible(false);
        selectBudgetLbl.setVisible(false);
        getBudgetBtn.setVisible(false);
        budgetTitleLbl.setText("New Budget");
        intervalLbl.setVisible(false);
        intervalTb.setVisible(false);
    }
    
    //edit budget
    public BudgetUI(BudgetCntl p, String v, String u, ArrayList<Budget> bl)
    {
        System.out.println("BudgetUI.constructor2");
        initComponents();
        parent = p;
        username = u;
        viewType = v;
        budgetList = bl;
        
        if(v.equals("new"))
        {
            budgetDropdown.setVisible(false);
            selectBudgetLbl.setVisible(false);
            getBudgetBtn.setVisible(false);
            budgetTitleLbl.setText("New Budget");
        }
        else if(v.equals("edit"))
        {
            budgetTitleLbl.setText("Edit Budget");
            String[] bNames = new String[bl.size()];
            for(int i = 0; i<bl.size(); i++)
            {
                bNames[i] = bl.get(i).getName();
            }

            //budgetDropdown = new JComboBox<>(bNames);
            budgetDropdown.setModel(new JComboBox<>(bNames).getModel());
        }
        
        intervalLbl.setVisible(false);
        intervalTb.setVisible(false);
       
    }
    
//    public BudgetUI(String v, String u)
//    {
//        initComponents();
//        System.out.println("BudgetUI.constructor");
//        viewType = v;
//        username = u;
//        
//        if(v.equals("new"))
//        {
//            budgetDropdown.setVisible(false);
//            budgetTitleLbl.setText("New Budget");
//        }
//        else if(v.equals("edit"))
//        {
//            budgetTitleLbl.setText("Edit Budget");
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        budgetTitleLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        nameLbl = new javax.swing.JLabel();
        budgetDropdown = new javax.swing.JComboBox<>();
        amountTb = new javax.swing.JTextField();
        amountLbl = new javax.swing.JLabel();
        nameTb1 = new javax.swing.JTextField();
        intervalLbl = new javax.swing.JLabel();
        intervalTb = new javax.swing.JTextField();
        getBudgetBtn = new javax.swing.JButton();
        selectBudgetLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        budgetTitleLbl.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        budgetTitleLbl.setText("___ Budget");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        nameLbl.setText("Budget Name");

        budgetDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        amountLbl.setText("Total Budget Amount");

        intervalLbl.setText("Interval Period (In days)");

        intervalTb.setText("0");

        getBudgetBtn.setText("Get Info");
        getBudgetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBudgetBtnActionPerformed(evt);
            }
        });

        selectBudgetLbl.setText("Select Budget");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(budgetTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectBudgetLbl)
                        .addGap(18, 18, 18)
                        .addComponent(budgetDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(getBudgetBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameLbl)
                            .addComponent(amountLbl)
                            .addComponent(intervalLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(amountTb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameTb1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(intervalTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveBtn)))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn)
                    .addComponent(budgetTitleLbl))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getBudgetBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(budgetDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selectBudgetLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intervalLbl)
                    .addComponent(intervalTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getBudgetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBudgetBtnActionPerformed
        String selectedBudget = budgetDropdown.getSelectedItem().toString();
        for(int i = 0; i<budgetList.size(); i++)
        {
            String b = budgetList.get(i).getName();
            if(selectedBudget.equals(b))
            {
                position = i;
                nameTb1.setText(b);
                amountTb.setText(String.valueOf(budgetList.get(i).getAmount()));
                intervalTb.setText(String.valueOf(budgetList.get(i).getIntervalPeriod()));
                break;
            }
        }
    }//GEN-LAST:event_getBudgetBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String amount = amountTb.getText();
        String regex = "[0-9]+"; 
        boolean isNumber = amount.matches(regex);
        String name = nameTb1.getText();
        
        if(name.equals("") || name.equals(null) || amount.equals("") || amount.equals(null))
        {
            JOptionPane.showMessageDialog(null, "Please fill in all text boxes", 
                    "Incorrect value type", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(isNumber == false)
        {
            JOptionPane.showMessageDialog(null, "Enter a dollar amount in 'amount' box", 
                    "Incorrect value type", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            if(viewType.equals("new"))
            {
                ArrayList<Category> c = new ArrayList<Category>();
                //budgetList.add(new Budget(nameTb1.getText(), Double.parseDouble(amountTb.getText()), Integer.parseInt(intervalTb.getText()), c));
                parent.addNewBudget(new Budget(nameTb1.getText(), Double.parseDouble(amountTb.getText()), Integer.parseInt(intervalTb.getText()), c));
                this.dispose();
            }
            else if(viewType.equals("edit"))
            {
                budgetList.get(position).setName(nameTb1.getText());
                budgetList.get(position).setAmount(Double.parseDouble(amountTb.getText()));
                budgetList.get(position).setIntervalPeriod(Integer.parseInt(intervalTb.getText()));
                parent.editBudget(budgetList);
                this.dispose();
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        parent.toNavigationUI();
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BudgetUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BudgetUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BudgetUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BudgetUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BudgetUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLbl;
    private javax.swing.JTextField amountTb;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> budgetDropdown;
    private javax.swing.JLabel budgetTitleLbl;
    private javax.swing.JButton getBudgetBtn;
    private javax.swing.JLabel intervalLbl;
    private javax.swing.JTextField intervalTb;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTb1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel selectBudgetLbl;
    // End of variables declaration//GEN-END:variables
}
