/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg412_budgetapp;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author aim5627
 */
public class CategoryUI extends javax.swing.JFrame {

    String username;
    String viewType;
    CategoryCntl parent;
    ArrayList<Budget> currentBL;
    ArrayList<Category> currentCL;
    int position;
    /**
     * Creates new form CategoryNavigationUI
     */
    public CategoryUI() {
        System.out.println("CategoryUI.constructor1");
        initComponents();
    }
    
     public CategoryUI(CategoryCntl p, String v, String u, ArrayList<Budget> BL, ArrayList<Category> CL){
        System.out.println("CategoryUI.constructor2");       
        initComponents();
        parent = p;
        username = u;
        viewType = v;
        currentBL = BL;
        currentCL = CL;
        
        String[] bNames = new String[currentBL.size()];
        for(int i = 0; i<currentBL.size(); i++)
        {
            bNames[i] = currentBL.get(i).getName();
        }
        budgetDropdown.setModel(new JComboBox<>(bNames).getModel());
        
        if(viewType.equals("new"))
        {
            categoryTitleLbl.setText("New Category");
            categoryDropdown.setVisible(false);
            selectCategoryLbl.setVisible(false);
            selectCategoryBtn.setVisible(false);
        }
        else if(viewType.equals("edit"))
        {
            categoryTitleLbl.setText("Edit Category");
            String[] cNames = new String[currentCL.size()];
            for(int i = 0; i<currentCL.size(); i++)
            {
                cNames[i] = currentCL.get(i).getName();
            }
            categoryDropdown.setModel(new JComboBox<>(cNames).getModel());
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        budgetTitleLbl = new javax.swing.JLabel();
        categoryTitleLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        nameLbl = new javax.swing.JLabel();
        categoryDropdown = new javax.swing.JComboBox<>();
        amountTb = new javax.swing.JTextField();
        amountLbl = new javax.swing.JLabel();
        nameTb = new javax.swing.JTextField();
        budgetNameLbl = new javax.swing.JLabel();
        budgetDropdown = new javax.swing.JComboBox<>();
        selectCategoryLbl = new javax.swing.JLabel();
        selectCategoryBtn = new javax.swing.JButton();

        budgetTitleLbl.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        budgetTitleLbl.setText("___ Budget");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        categoryTitleLbl.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        categoryTitleLbl.setText("___ Category");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        nameLbl.setText("Category Name");

        categoryDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        amountLbl.setText("Total Budget Amount");

        budgetNameLbl.setText("Budget Name");

        budgetDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectCategoryLbl.setText("Select Category");

        selectCategoryBtn.setText("Get Info");
        selectCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCategoryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(categoryTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nameLbl)
                                    .addComponent(amountLbl)
                                    .addComponent(budgetNameLbl)
                                    .addComponent(selectCategoryLbl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(amountTb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(budgetDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(categoryDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(selectCategoryBtn)))
                                .addGap(19, 19, 19)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryTitleLbl)
                    .addComponent(backBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectCategoryLbl)
                    .addComponent(selectCategoryBtn))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLbl)
                    .addComponent(amountTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(budgetDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(budgetNameLbl))
                .addGap(29, 29, 29)
                .addComponent(saveBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        parent.toNavigationUI();
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void selectCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCategoryBtnActionPerformed
        String selectedCategory = categoryDropdown.getSelectedItem().toString();
        for(int i = 0; i<currentCL.size(); i++)
        {
            String c = currentCL.get(i).getName();
            if(selectedCategory.equals(c))
            {
                position = i;
                nameTb.setText(c);
                amountTb.setText(String.valueOf(currentCL.get(i).getAmount()));
                //intervalTb.setText(String.valueOf(currentCL.get(i).getIntervalPeriod()));
                budgetDropdown.setSelectedItem(currentCL.get(i).getBudgetName());
                break;
            }
        }
    }//GEN-LAST:event_selectCategoryBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String amount = amountTb.getText();
        String regex = "[0-9]+"; 
        boolean isNumber = amount.matches(regex);
        String name = nameTb.getText();
        
        if(name.equals("") || name.equals(null) || amount.equals("") || amount.equals(null))
        {
            JOptionPane.showMessageDialog(null, "Please fill in all text boxes", 
                    "Incorrect value type", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(isNumber == false)
        {
            JOptionPane.showMessageDialog(null, "Enter a dollar amount in 'amount' box", 
                    "Incorrect value type", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            if(viewType.equals("new"))
            {
                ArrayList<Transaction> t = new ArrayList<Transaction>();
                //budgetList.add(new Budget(nameTb1.getText(), Double.parseDouble(amountTb.getText()), Integer.parseInt(intervalTb.getText()), c));
                parent.addNewCategory(new Category(nameTb.getText(), Double.parseDouble(amountTb.getText()), budgetDropdown.getSelectedItem().toString(), t));
                this.dispose();
            }
            else if(viewType.equals("edit"))
            {
                currentCL.get(position).setName(nameTb.getText());
                currentCL.get(position).setAmount(Double.parseDouble(amountTb.getText()));
                currentCL.get(position).setBudgetName(categoryDropdown.getSelectedItem().toString());
                parent.editCategory(currentCL);
                this.dispose();
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoryUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLbl;
    private javax.swing.JTextField amountTb;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> budgetDropdown;
    private javax.swing.JLabel budgetNameLbl;
    private javax.swing.JLabel budgetTitleLbl;
    private javax.swing.JComboBox<String> categoryDropdown;
    private javax.swing.JLabel categoryTitleLbl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTb;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton selectCategoryBtn;
    private javax.swing.JLabel selectCategoryLbl;
    // End of variables declaration//GEN-END:variables
}
