/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg412_budgetapp;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
/**
 *
 * @author aim5627
 */
public class TransactionUI extends javax.swing.JFrame {
    TransactionCntl parent;
    String username;
    ArrayList<Category> categoryList;
    
    
    /**
     * Creates new form TransactionUI
     */
    public TransactionUI() {
        System.out.println("TransactionUI.constructor1");
        initComponents();
    }
    
    public TransactionUI(TransactionCntl p, String u, ArrayList<Category> cAL) {
        System.out.println("TransactionUI.constructor2");
        initComponents();
        parent = p;
        username = u;
        categoryList = cAL;
        
        String[] categoryNamesList = new String[categoryList.size()];
        
        for(int i = 0; i<categoryList.size(); i++)
        {
            categoryNamesList[i] = categoryList.get(i).getName();
        }
        CategoryComboBox.setModel(new JComboBox<>(categoryNamesList).getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        backBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        amountLbl = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        returnRB = new javax.swing.JRadioButton();
        withdrawRB = new javax.swing.JRadioButton();
        TransactionTypeLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        monthTF = new javax.swing.JTextField();
        dayTF = new javax.swing.JTextField();
        yearTF = new javax.swing.JTextField();
        purchaseLocationLbl = new javax.swing.JLabel();
        purchaseLocationTF = new javax.swing.JTextField();
        DescriptionLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescriptionTB = new javax.swing.JTextArea();
        categoryLbl = new javax.swing.JLabel();
        CategoryComboBox = new javax.swing.JComboBox<>();
        SaveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        titleLbl.setText("New Transaction");

        nameLbl.setText("Name:");

        amountLbl.setText("Amount:");

        returnRB.setText("Return");

        withdrawRB.setText("Withdraw");

        TransactionTypeLbl.setText("Transaction Type:");

        dateLbl.setText("Date:");

        purchaseLocationLbl.setText("Purchase Location:");

        DescriptionLbl.setText("Description:");

        DescriptionTB.setColumns(20);
        DescriptionTB.setRows(5);
        jScrollPane1.setViewportView(DescriptionTB);

        categoryLbl.setText("Category:");

        CategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nameLbl)
                                    .addComponent(TransactionTypeLbl)
                                    .addComponent(amountLbl)
                                    .addComponent(dateLbl)
                                    .addComponent(purchaseLocationLbl)
                                    .addComponent(DescriptionLbl)
                                    .addComponent(categoryLbl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(amountTF, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(NameTF))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(monthTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(returnRB))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(withdrawRB))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(yearTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(purchaseLocationTF, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 103, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titleLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backBtn))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SaveBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(titleLbl))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountLbl))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnRB)
                    .addComponent(withdrawRB)
                    .addComponent(TransactionTypeLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLbl)
                    .addComponent(monthTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchaseLocationLbl)
                    .addComponent(purchaseLocationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescriptionLbl)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLbl)
                    .addComponent(CategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(SaveBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        parent.backToMain();
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        //String n, double a, String tt, String cn, int m, int d, int y, String pl, String descr
        String month = monthTF.getText();
        String day = dayTF.getText();
        String year = yearTF.getText();
        String amount = amountTF.getText();
        String regex = "[0-9]+"; 
        boolean isMonth = month.matches(regex);
        boolean isDay = day.matches(regex);
        boolean isYear = year.matches(regex);
        boolean isAmount = amount.matches(regex);
        String name = NameTF.getText();
        String purchaseLocation = purchaseLocationTF.getText();
        String desc = DescriptionTB.getText();
        //
        if(name.equals("") || name.equals(null) || amount.equals("") || amount.equals(null) ||
                month.equals("") || month.equals(null) || day.equals("") || day.equals(null) ||
                year.equals("") || year.equals(null) || purchaseLocation.equals("") || 
                purchaseLocation.equals(null) || desc.equals(null) || desc.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please fill in all text boxes", 
                    "Incorrect value type", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(isAmount == false)
        {
            JOptionPane.showMessageDialog(null, "Enter a dollar amount in 'amount' box", 
                    "Incorrect value type", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(isMonth == false || isDay == false || isYear == false)
        {
            JOptionPane.showMessageDialog(null, "Enter a number amount for the date boxes", 
                    "Incorrect value type", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(returnRB.isSelected() && withdrawRB.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Return & Withdaw are selected, "
                    + "please disselect 1", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(!returnRB.isSelected() && !withdrawRB.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Please select Return or Withdaw ", 
                    "Warning", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
                if(returnRB.isSelected())
                {
                    parent.newTransaction(NameTF.getText(), Double.parseDouble(amountTF.getText()), "return", CategoryComboBox.getSelectedItem().toString(), Integer.parseInt(monthTF.getText()), Integer.parseInt(dayTF.getText()), Integer.parseInt(yearTF.getText()), purchaseLocationTF.getText(), DescriptionTB.getText());
                    this.dispose();
                }
                else if(withdrawRB.isSelected())
                {
                    parent.newTransaction(NameTF.getText(), Double.parseDouble(amountTF.getText()), "withdraw", CategoryComboBox.getSelectedItem().toString(), Integer.parseInt(monthTF.getText()), Integer.parseInt(dayTF.getText()), Integer.parseInt(yearTF.getText()), purchaseLocationTF.getText(), DescriptionTB.getText());
                    this.dispose();
                }
            }    
        //}
    }//GEN-LAST:event_SaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CategoryComboBox;
    private javax.swing.JLabel DescriptionLbl;
    private javax.swing.JTextArea DescriptionTB;
    private javax.swing.JTextField NameTF;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel TransactionTypeLbl;
    private javax.swing.JLabel amountLbl;
    private javax.swing.JTextField amountTF;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel categoryLbl;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextField dayTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField monthTF;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel purchaseLocationLbl;
    private javax.swing.JTextField purchaseLocationTF;
    private javax.swing.JRadioButton returnRB;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JRadioButton withdrawRB;
    private javax.swing.JTextField yearTF;
    // End of variables declaration//GEN-END:variables
}
